<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MySubjects.aspx.cs" Inherits="Quizify.Subjects.MySubjects" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Subjects</title>
</head>
<body>
    <form id="form1" runat="server">
        <h1>Subjects</h1>

        <!-- GridView for editing and deleting subjects -->
        <asp:GridView ID="SubjectsGridViewa" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            OnRowCancelingEdit="SubjectsGridViewa_RowCancelingEdit" 
            OnRowDeleting="SubjectsGridViewa_RowDeleting" 
            OnRowEditing="SubjectsGridViewa_RowEditing" 
            OnRowUpdating="SubjectsGridViewa_RowUpdating" 
            DataKeyNames="Id">
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Subject Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" />
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="SubjectLink" runat="server" Text='Questions' NavigateUrl='<%# "EditQuestion.aspx?id=" + Eval("Id") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

        <!-- Form for adding new subjects -->
        <p>&nbsp;</p>
        <asp:Label ID="lblSubjectName" runat="server" Text="Name:"></asp:Label>
        <asp:TextBox ID="tbSubName" runat="server"></asp:TextBox>
        <br /><br />

        <asp:Label ID="lblSubDesc" runat="server" Text="Description:"></asp:Label>
        <asp:TextBox ID="tbSubDesc" runat="server" TextMode="MultiLine"></asp:TextBox>
        <br /><br />

        <!-- Add a ValidationGroup to the button and validators -->
        <asp:Button ID="btnAddSubject" runat="server" OnClick="btnAddSubject_Click" Text="Add Subject" ValidationGroup="AddSubjectGroup" />
        <br />

        <asp:ValidationSummary ID="vsMySubject" runat="server" ValidationGroup="AddSubjectGroup" />
        <asp:RequiredFieldValidator ID="rfvName" runat="server" ControlToValidate="tbSubName" Display="None" ErrorMessage="Name is required" ValidationGroup="AddSubjectGroup"></asp:RequiredFieldValidator>
        <asp:RequiredFieldValidator ID="rfvSubDesc" runat="server" ControlToValidate="tbSubDesc" Display="None" ErrorMessage="Description is required" ValidationGroup="AddSubjectGroup"></asp:RequiredFieldValidator>
    </form>
</body>
</html>
